### PR TITLE
Admissions

### PR DESCRIPTION
**Pull request by Nerian**
Create a admission, with dynamic questions. 
Create a submission, answering those questions.

### CODE REVIEW

**Comment by jordanbyron** [comment]
@Nerian & @justinramel great first push on this feature. I haven't pulled down the code, but there were a few minor things I noticed which either of you can easily fix:
1. Empty tests: Just remove them. As a general rule of thumb if I am using `rails generate XXX` I either immediately start writing tests or I throw away the empty test files.
2. Stock generated views: Just remove them. I think the only one I noticed was `app/views/submissions/create.html.haml`, but just be careful you aren't checking in files you don't need.
3. Setup instructions are probably a bit too in depth and specific. There are tons of guides on getting up and running with postgres, and I'd rather not have to maintain one in our project's README.
4. Perhaps this is coming in a later version, but we also want to allow new applicants to update their user information at that time. So `app/views/submissions/new.html.haml` should display a form which they can update their `Person` record. 

I think that's enough to keep you busy for now. Let me know once you've made those changes or if you have any questions. Great work so far :smile:

**Comment by Nerian** [comment]
1,2,3 done :)

Regarding 4: Will the user be logged in when in app/views/submissions/new.html.haml  ?

**Comment by jordanbyron** [comment]
> 1,2,3 done :)

Great!

> Regarding 4: Will the user be logged in when in app/views/submissions/new.html.haml ?

The user should have authenticated with GitHub and have an `Authorization` record in the database before they can view the submission page. For right now let's assume they do not have a user account created until they submit their application form. Does that make sense?

**Comment by Nerian** [comment]
@jordanbyron So we create the user (Person model) in that view?

**Comment by jordanbyron** [comment]
> @jordanbyron So we create the user (People model) in that view?

That is correct.

**Comment by Nerian** [comment]
Job done sir!

**Pull request closed without merging**
